<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="icon" href="<?php bloginfo('template_directory');?>/images/favicon.png">
    <title>
        <?php wp_title('|', true, 'right'); ?>
        <?php bloginfo('name'); ?>
    </title>
    <?php  wp_head(); ?>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112228636-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112228636-1');
</script>

    <script src='https://www.google.com/recaptcha/api.js'></script>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "3313 S. Black Oak Drive",
    "addressLocality": "Stillwater",
    "addressRegion": "Oklahoma",
    "postalCode":"74074"
    },
    "description": "Webby D is a full service web design and web development company based in Stillwater, OK. Contact us for website design and development",
  "name" : "WEBBY D",
  "image" : [ "http://webby-d.com/wp-content/themes/scottrmontgomery/images/av.png", "http://webby-d.com/wp-content/themes/scottrmontgomery/images/logo.svg" ],
    "geo": {
    "@type": "GeoCoordinates",
    "latitude": "36.0851474",
    "longitude": "-97.1018326"
    }
}
</script>
</head>

<body <?php body_class(); ?>>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="page-nav">
                <?php include 'includes/social.php'; ?>
        <div class="container header-container">
            <a href="<?php echo home_url(); ?>">
              <img class="logo" src="http://www.webby-d.com/wp-content/themes/scottrmontgomery/images/logo.svg" alt="Scott R Montgomery Logo">
            </a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <?php
            $args = array(
              'menu' => 'header-menu',
              'menu_class' => 'nav navbar-nav',
              'container' => 'false');
            wp_nav_menu($args); ?>
            </div>
            <!--/.navbar-collapse -->
        </div>
    </nav>
